export type CatalogMission={title:string;description:string;scenario:string;difficulty:"BEGINNER"|"INTERMEDIATE"|"ADVANCED"|"BOSS";xpReward:number;estimatedMinutes:number;skill:string};
export const careerMissionCatalog:Record<string,CatalogMission[]>={
 "Frontend Developer":[
  {title:"Rebuild an accessible product landing page",description:"Create a responsive interface from a product brief with semantic HTML and modern CSS.",scenario:"A startup needs an accessible launch page that performs well across phones, tablets, and desktops.",difficulty:"BEGINNER",xpReward:100,estimatedMinutes:180,skill:"HTML & CSS"},
  {title:"Build a typed component library",description:"Create reusable React components with TypeScript, variants, and documentation.",scenario:"A product team needs consistent buttons, inputs, cards, and feedback components for three applications.",difficulty:"INTERMEDIATE",xpReward:250,estimatedMinutes:300,skill:"React"},
  {title:"Ship an interactive analytics interface",description:"Build filters, charts, loading states, and accessible data views.",scenario:"A business team needs a fast analytics dashboard that works with live API data and handles failure states.",difficulty:"ADVANCED",xpReward:500,estimatedMinutes:480,skill:"Frontend Architecture"},
  {title:"Frontend performance rescue",description:"Audit and improve rendering, accessibility, bundle size, and Core Web Vitals.",scenario:"A high-traffic storefront is losing conversions because its interface is slow and difficult to navigate.",difficulty:"BOSS",xpReward:1000,estimatedMinutes:900,skill:"Performance"}],
 "Backend Developer":[
  {title:"Design a validated REST API",description:"Create predictable CRUD endpoints with validation and structured errors.",scenario:"A mobile team needs a documented API for managing customers, orders, and inventory.",difficulty:"BEGINNER",xpReward:100,estimatedMinutes:210,skill:"API Design"},
  {title:"Add secure role-based authentication",description:"Protect resources using sessions, authorization checks, and audit logs.",scenario:"A SaaS platform needs separate permissions for members, managers, and administrators.",difficulty:"INTERMEDIATE",xpReward:250,estimatedMinutes:360,skill:"Security"},
  {title:"Build a resilient job processing service",description:"Implement queued work, retries, idempotency, and failure monitoring.",scenario:"A media platform must process uploads reliably without blocking normal API traffic.",difficulty:"ADVANCED",xpReward:500,estimatedMinutes:540,skill:"Systems"},
  {title:"Scale a production commerce backend",description:"Design caching, database indexes, observability, and safe deployment controls.",scenario:"A commerce API must survive a tenfold traffic increase during a major sale.",difficulty:"BOSS",xpReward:1000,estimatedMinutes:960,skill:"Scalability"}],
 "Full-Stack Developer":[
  {title:"Build a customer feedback portal",description:"Create authentication, forms, a database, and a polished responsive interface.",scenario:"A product team needs one place to collect, organize, and respond to customer feedback.",difficulty:"BEGINNER",xpReward:100,estimatedMinutes:300,skill:"Full-Stack"},
  {title:"Create a team project tracker",description:"Build collaborative CRUD workflows, permissions, and activity history.",scenario:"A distributed team needs a secure tracker for projects, tasks, owners, and deadlines.",difficulty:"INTERMEDIATE",xpReward:250,estimatedMinutes:480,skill:"Product Engineering"},
  {title:"Ship a subscription analytics platform",description:"Connect billing events, data aggregation, dashboards, and protected APIs.",scenario:"A SaaS founder needs trustworthy subscription metrics and customer health signals.",difficulty:"ADVANCED",xpReward:500,estimatedMinutes:720,skill:"SaaS"},
  {title:"Launch a production multi-tenant SaaS",description:"Deliver a secure, tested, observable application from database to deployment.",scenario:"An accelerator company needs a multi-tenant product ready for its first paying organizations.",difficulty:"BOSS",xpReward:1000,estimatedMinutes:1200,skill:"Architecture"}],
 "QA Automation Engineer":[
  {title:"Write a critical-path browser test suite",description:"Automate login, navigation, form validation, and checkout journeys.",scenario:"A release team needs reliable smoke tests before every production deployment.",difficulty:"BEGINNER",xpReward:100,estimatedMinutes:180,skill:"Browser Testing"},
  {title:"Build an API contract test harness",description:"Validate API schemas, error behavior, authorization, and edge cases.",scenario:"Frontend teams keep breaking because backend response contracts change without warning.",difficulty:"INTERMEDIATE",xpReward:250,estimatedMinutes:300,skill:"API Testing"},
  {title:"Design a maintainable CI quality pipeline",description:"Run parallel tests, collect artifacts, quarantine flakes, and report trends.",scenario:"A growing test suite is slow and flaky, delaying every engineering team.",difficulty:"ADVANCED",xpReward:500,estimatedMinutes:480,skill:"CI/CD"},
  {title:"Lead a full release quality audit",description:"Create a risk model covering functionality, accessibility, performance, and security.",scenario:"A financial product needs evidence-based release approval before a major launch.",difficulty:"BOSS",xpReward:1000,estimatedMinutes:840,skill:"Quality Strategy"}],
 "UI/UX Developer":[
  {title:"Prototype an accessible onboarding flow",description:"Design and code a clear multi-step experience with useful feedback.",scenario:"New users abandon a complex onboarding process before reaching their first success.",difficulty:"BEGINNER",xpReward:100,estimatedMinutes:210,skill:"Interaction Design"},
  {title:"Create a coded design system",description:"Define tokens, components, states, responsive rules, and usage guidance.",scenario:"Three product teams need one accessible visual language that designers and developers can share.",difficulty:"INTERMEDIATE",xpReward:250,estimatedMinutes:390,skill:"Design Systems"},
  {title:"Redesign a complex workflow",description:"Research usability problems and implement a tested, production-ready workflow.",scenario:"Support agents lose time and make costly mistakes in a confusing case-management interface.",difficulty:"ADVANCED",xpReward:500,estimatedMinutes:540,skill:"UX Engineering"},
  {title:"Deliver an inclusive product experience",description:"Audit, redesign, code, and validate an end-to-end experience for diverse users.",scenario:"A public-service application must meet strict accessibility and usability standards.",difficulty:"BOSS",xpReward:1000,estimatedMinutes:900,skill:"Inclusive Design"}],
 "Figma Designer":[
  {title:"Design a mobile app onboarding in Figma",description:"Create user flows, wireframes, polished screens, and a clickable prototype.",scenario:"A wellness app needs an onboarding experience that explains value without overwhelming new users.",difficulty:"BEGINNER",xpReward:100,estimatedMinutes:180,skill:"Figma Prototyping"},
  {title:"Build a scalable Figma component library",description:"Create variables, auto layout components, variants, and documentation.",scenario:"A design team needs a library that stays consistent across web and mobile products.",difficulty:"INTERMEDIATE",xpReward:250,estimatedMinutes:360,skill:"Figma Systems"},
  {title:"Prototype a responsive SaaS dashboard",description:"Design responsive layouts, interactive states, tables, charts, and empty states.",scenario:"A B2B startup needs a testable prototype before engineers build its analytics product.",difficulty:"ADVANCED",xpReward:500,estimatedMinutes:480,skill:"Product Design"},
  {title:"Create and validate a complete product prototype",description:"Turn research into flows, high-fidelity UI, a prototype, and usability findings.",scenario:"Investors need proof that a new marketplace concept is usable before funding development.",difficulty:"BOSS",xpReward:1000,estimatedMinutes:840,skill:"UX Prototyping"}],
 "Web Designer":[
  {title:"Design a responsive local business website",description:"Create a visual direction, page hierarchy, and responsive website design.",scenario:"A local studio needs a trustworthy website that turns mobile visitors into qualified leads.",difficulty:"BEGINNER",xpReward:100,estimatedMinutes:210,skill:"Web Design"},
  {title:"Create a conversion-focused ecommerce design",description:"Design product discovery, product pages, cart, and checkout states.",scenario:"A growing lifestyle brand needs a storefront that feels premium and improves conversion.",difficulty:"INTERMEDIATE",xpReward:250,estimatedMinutes:390,skill:"Ecommerce UX"},
  {title:"Build a responsive editorial design system",description:"Define grids, typography, content modules, and responsive behavior.",scenario:"A digital magazine needs a flexible system for long-form stories and daily news.",difficulty:"ADVANCED",xpReward:500,estimatedMinutes:510,skill:"Responsive Systems"},
  {title:"Redesign and validate a complete marketing site",description:"Lead discovery, information architecture, visual design, prototyping, and handoff.",scenario:"A technology company needs a full website redesign before an international product launch.",difficulty:"BOSS",xpReward:1000,estimatedMinutes:900,skill:"Creative Direction"}]
};
