"use client";
import Link from "next/link";
import {useCallback,useEffect,useMemo,useState} from "react";
import {CheckCircle2,Clock,LoaderCircle,Lock,Search,Star,Target} from "lucide-react";
import {createClient} from "@/lib/supabase/client";
type Mission={id:string;slug:string;title:string;description:string;difficulty:string;xpReward:number;estimatedMinutes:number;boss:boolean;career:{name:string}};
const filters=["All","Beginner","Intermediate","Advanced","Boss","Available","Completed","Locked"];
export default function Page(){const[filter,setFilter]=useState("All");const[query,setQuery]=useState("");const[missions,setMissions]=useState<Mission[]|null>(null);const[completed,setCompleted]=useState<string[]>([]);const[career,setCareer]=useState("");const[error,setError]=useState("");
 useEffect(()=>{void createClient().auth.getSession().then(async({data:{session}})=>{if(!session)throw new Error("Please sign in.");const response=await fetch("/api/missions",{cache:"no-store",headers:{Authorization:`Bearer ${session.access_token}`}});const result=await response.json();if(!response.ok)throw new Error(result.message);setMissions(result.missions);setCompleted(result.completedMissionIds);setCareer(result.missions[0]?.career.name||"Your career")}).catch(e=>setError(e instanceof Error?e.message:"Could not load missions."))},[]);
 const statusFor=useCallback((mission:Mission)=>completed.includes(mission.id)?"Completed":mission.difficulty==="BOSS"&&completed.length<3?"Locked":mission.difficulty==="ADVANCED"&&completed.length<1?"Locked":"Available",[completed]);
 const shown=useMemo(()=>missions?.filter(mission=>{const status=statusFor(mission);const difficulty=mission.difficulty[0]+mission.difficulty.slice(1).toLowerCase();return(filter==="All"||difficulty===filter||status===filter)&&mission.title.toLowerCase().includes(query.toLowerCase())})??[],[missions,filter,query,statusFor]);
 if(error)return <div className="card dashboard-state"><Target/><h1 className="heading">Missions unavailable</h1><p>{error}</p></div>;if(!missions)return <div className="card dashboard-state"><LoaderCircle className="animate-spin"/><h2 className="heading">Loading your career missions…</h2></div>;
 return <><div className="eyebrow">{career} · {missions.length} unique missions</div><h1 className="heading" style={{fontSize:42,marginBottom:8}}>Choose your next mission.</h1><p className="muted">These missions are designed specifically for your selected career path.</p><div className="mission-toolbar"><label className="mission-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search your missions" aria-label="Search missions"/></label><div className="mission-filters">{filters.map(item=><button key={item} onClick={()=>setFilter(item)} className={filter===item?"active":""}>{item}</button>)}</div></div><div className="grid-3">{shown.map(mission=>{const status=statusFor(mission);const content=<><div className="mission-card-top"><span className="badge">{mission.difficulty.replace("_"," ")}</span><span className={`mission-status ${status.toLowerCase()}`}>{status==="Completed"?<CheckCircle2 size={13}/>:status==="Locked"?<Lock size={13}/>:<Star size={13}/>} {status}</span></div><h3 className="heading">{mission.title}</h3><p>{mission.description}</p><div className="mission-card-footer"><span><Star size={14}/>{mission.xpReward} XP</span><span><Clock size={14}/>{Math.max(1,Math.round(mission.estimatedMinutes/60))}h</span><span>{mission.career.name}</span></div>{status==="Locked"&&<small className="mission-lock-note">Complete earlier missions to unlock</small>}</>;return status==="Locked"?<div className="card mission-card locked" key={mission.id}>{content}</div>:<Link href={`/dashboard/missions/${mission.slug}`} className={`card mission-card ${status==="Completed"?"completed":""}`} key={mission.id}>{content}</Link>})}</div>{!shown.length&&<div className="card empty-missions"><Lock/><h2>No missions found</h2><p>Try a different search or filter.</p></div>}</>}
