"use client";

import { useEffect, useRef, useState } from "react";
import { Bot, BrainCircuit, LoaderCircle, MessageCircleQuestion, RotateCcw, Send, ShieldCheck, Sparkles, UserRound } from "lucide-react";
import { toast } from "sonner";
import { createClient } from "@/lib/supabase/client";

type ChatMessage={role:"user"|"assistant";content:string};
const greeting:ChatMessage={role:"assistant",content:"Hi! I’m your SkillVerse AI Mentor. Ask me about your roadmap, missions, portfolio, learning strategy, or how to use SkillVerse."};
const suggestions=["What should I work on next?","Help me plan my current mission","How can I improve my portfolio?","Explain XP and achievements"];

export default function Page(){
  const[messages,setMessages]=useState<ChatMessage[]>(()=>{if(typeof window==="undefined")return[greeting];try{const parsed=JSON.parse(sessionStorage.getItem("skillverse-ai-chat")||"[]");return Array.isArray(parsed)&&parsed.length?parsed:[greeting]}catch{return[greeting]}});const[input,setInput]=useState("");const[sending,setSending]=useState(false);const bottom=useRef<HTMLDivElement>(null);
  useEffect(()=>{bottom.current?.scrollIntoView({behavior:"smooth"})},[messages,sending]);
  async function sendMessage(text=input){const content=text.trim();if(!content||sending)return;const next=[...messages,{role:"user" as const,content}];setMessages(next);setInput("");setSending(true);try{const{data:{session}}=await createClient().auth.getSession();if(!session)throw new Error("Please log in to use the AI Mentor.");const response=await fetch("/api/ai-mentor",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({messages:next.slice(-12).filter(message=>message!==greeting)})});const data=await response.json();if(!response.ok)throw new Error(data.message);const updated=[...next,{role:"assistant" as const,content:data.answer}];setMessages(updated);sessionStorage.setItem("skillverse-ai-chat",JSON.stringify(updated.slice(-20)))}catch(error){toast.error(error instanceof Error?error.message:"The AI Mentor could not respond.");setMessages(next)}finally{setSending(false)}}
  function clearChat(){setMessages([greeting]);sessionStorage.removeItem("skillverse-ai-chat");toast.success("Conversation cleared.")}
  return <div className="ai-mentor-page"><header className="ai-mentor-heading"><div><div className="eyebrow"><Sparkles size={14}/>Career-aware guidance</div><h1 className="heading">SkillVerse AI Mentor</h1><p>Plan missions, understand the platform, and turn your roadmap into practical next steps.</p></div><div className="ai-status"><i/><span><strong>AI mentor</strong><small>Ready to guide</small></span></div></header>
    <div className="ai-mentor-layout"><aside className="ai-mentor-sidebar"><section className="card ai-guide-card"><div className="ai-guide-icon"><BrainCircuit/></div><h2>Your campaign copilot</h2><p>The mentor uses your active career, level, and XP to make its guidance more relevant.</p><div className="ai-guide-points"><span><MessageCircleQuestion/>Ask about SkillVerse</span><span><Sparkles/>Plan career missions</span><span><ShieldCheck/>Your API key stays server-side</span></div></section><section><div className="eyebrow">Try asking</div><div className="ai-suggestions">{suggestions.map(item=><button key={item} onClick={()=>sendMessage(item)} disabled={sending}>{item}<Send size={13}/></button>)}</div></section><button className="btn btn-ghost ai-clear" onClick={clearChat}><RotateCcw size={15}/>Clear conversation</button></aside>
      <section className="ai-chat-shell"><div className="ai-chat-top"><span><Bot size={17}/>MENTOR CHANNEL</span><span className="ai-encrypted"><ShieldCheck size={13}/>Authenticated</span></div><div className="ai-chat-messages" aria-live="polite">{messages.map((message,index)=><article className={`ai-message ${message.role}`} key={`${message.role}-${index}`}><div className="ai-message-avatar">{message.role==="assistant"?<Bot/>:<UserRound/>}</div><div><span>{message.role==="assistant"?"SkillVerse Mentor":"You"}</span><p>{message.content}</p></div></article>)}{sending&&<article className="ai-message assistant"><div className="ai-message-avatar"><Bot/></div><div><span>SkillVerse Mentor</span><div className="ai-typing"><i/><i/><i/></div></div></article>}<div ref={bottom}/></div><form className="ai-composer" onSubmit={event=>{event.preventDefault();void sendMessage()}}><textarea aria-label="Message the SkillVerse AI Mentor" value={input} onChange={event=>setInput(event.target.value)} onKeyDown={event=>{if(event.key==="Enter"&&!event.shiftKey){event.preventDefault();void sendMessage()}}} maxLength={2000} rows={2} placeholder="Ask about your roadmap, a mission, or your career plan…"/><div><small>{input.length}/2000 · Shift + Enter for a new line</small><button className="btn btn-primary" disabled={sending||!input.trim()}>{sending?<LoaderCircle className="animate-spin"/>:<Send/>}<span>Send</span></button></div></form></section>
    </div><p className="ai-disclaimer">AI guidance can make mistakes. Verify important career, security, and technical decisions.</p></div>;
}
