"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, CheckCircle2, Code2, Gamepad2, Lightbulb, LoaderCircle, LockKeyhole, RotateCcw, Sparkles, Trophy } from "lucide-react";
import { toast } from "sonner";
import { createClient } from "@/lib/supabase/client";

type Level={title:string;brief:string;hint:string;starter:string;solution:Record<string,string>;items:number;labels:string[]};
const levels:Level[]=[
  {title:"Split the workspace",brief:"Create two equal columns for the editor and preview.",hint:"Use repeat() to create two identical tracks.",starter:".grid {\n  display: grid;\n  /* your code */\n}",solution:{gridTemplateColumns:"repeat(2, 1fr)"},items:2,labels:["CODE","PREVIEW"]},
  {title:"Build the dashboard",brief:"Create a 3-column dashboard with a 16px gap.",hint:"You need grid-template-columns and gap.",starter:".grid {\n  display: grid;\n  /* your code */\n}",solution:{gridTemplateColumns:"repeat(3, 1fr)",gap:"16px"},items:6,labels:["01","02","03","04","05","06"]},
  {title:"Feature the first card",brief:"Make the first card span two columns in a 3-column grid.",hint:"Style .item-1 with grid-column.",starter:".grid {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n  gap: 12px;\n}\n\n.item-1 {\n  /* your code */\n}",solution:{item1GridColumn:"span 2"},items:5,labels:["FEATURED","02","03","04","05"]},
  {title:"Create the app shell",brief:"Build a 110px sidebar and flexible content column.",hint:"The first track is fixed; the second consumes remaining space.",starter:".grid {\n  display: grid;\n  /* your code */\n  gap: 14px;\n}",solution:{gridTemplateColumns:"110px 1fr"},items:2,labels:["NAV","CONTENT"]},
  {title:"Center the launch",brief:"Create three equal columns and center every card inside its grid area.",hint:"justify-items controls alignment inside columns.",starter:".grid {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n  /* your code */\n}",solution:{justifyItems:"center"},items:3,labels:["SHIP","LEARN","LEVEL UP"]},
];
const allowedCareers=["Frontend Developer","Full-Stack Developer"];

function parseCss(css:string){const grid=css.match(/\.grid\s*\{([^}]*)\}/)?.[1]||"";const first=css.match(/\.item-1\s*\{([^}]*)\}/)?.[1]||"";const value=(block:string,name:string)=>block.match(new RegExp(`${name}\\s*:\\s*([^;\\n}]+)`))?.[1].trim()||"";return{gridTemplateColumns:value(grid,"grid-template-columns"),gridTemplateRows:value(grid,"grid-template-rows"),gap:value(grid,"gap"),justifyItems:value(grid,"justify-items"),alignItems:value(grid,"align-items"),item1GridColumn:value(first,"grid-column")}}
function normalize(value:string){return value.toLowerCase().replace(/\s+/g," ").replace(/\s*,\s*/g,",").trim()}

export default function Page(){
  const[level,setLevel]=useState(0);const[code,setCode]=useState(levels[0].starter);const[career,setCareer]=useState("");const[loading,setLoading]=useState(true);const[completed,setCompleted]=useState<number[]>(()=>{if(typeof window==="undefined")return[];try{return JSON.parse(localStorage.getItem("skillverse-css-grid-levels")||"[]")}catch{return[]}});const[showHint,setShowHint]=useState(false);const[won,setWon]=useState(false);
  useEffect(()=>{void createClient().auth.getSession().then(async({data:{session}})=>{if(!session)throw new Error("Please sign in.");const response=await fetch("/api/profile",{cache:"no-store",headers:{Authorization:`Bearer ${session.access_token}`}});const data=await response.json();if(!response.ok)throw new Error(data.message);setCareer(data.profile?.careers?.[0]?.career?.name||"")}).catch(error=>toast.error(error instanceof Error?error.message:"Could not load game." )).finally(()=>setLoading(false))},[]);
  const parsed=useMemo(()=>parseCss(code),[code]);const current=levels[level];const correct=Object.entries(current.solution).every(([key,value])=>normalize(parsed[key as keyof typeof parsed])===normalize(value));
  const liveStyle:React.CSSProperties={display:"grid",gridTemplateColumns:parsed.gridTemplateColumns||undefined,gridTemplateRows:parsed.gridTemplateRows||undefined,gap:parsed.gap||undefined,justifyItems:parsed.justifyItems||undefined,alignItems:parsed.alignItems||undefined};
  function selectLevel(index:number){setLevel(index);setCode(levels[index].starter);setShowHint(false);setWon(false)}
  function run(){if(!correct){toast.error("Not quite. Compare your grid with the target and try the hint.");return}const next=[...new Set([...completed,level])];setCompleted(next);localStorage.setItem("skillverse-css-grid-levels",JSON.stringify(next));setWon(true);toast.success(`Level complete · +${(level+1)*20} practice XP`)}
  if(loading)return <div className="card dashboard-state"><LoaderCircle className="animate-spin"/><h2>Loading CSS Grid arena…</h2></div>;
  if(!allowedCareers.includes(career))return <div className="game-locked card"><LockKeyhole/><div className="eyebrow">Career challenge</div><h1 className="heading">CSS Grid Arena</h1><p>This game is designed for Frontend and Full-Stack Developer learning paths. Your current path is <strong>{career||"not selected"}</strong>.</p><Link className="btn btn-primary" href="/onboarding">Choose an eligible career</Link></div>;
  return <div className="grid-game-page"><header className="game-heading"><div><div className="eyebrow"><Gamepad2 size={14}/>Interactive code lab</div><h1 className="heading">CSS Grid Arena</h1><p>Write real CSS. Match the target. Master layout one level at a time.</p></div><div className="game-progress"><Trophy/><strong>{completed.length}/{levels.length}</strong><span>levels cleared</span></div></header>
    <div className="game-levels" aria-label="Game levels">{levels.map((item,index)=><button key={item.title} onClick={()=>selectLevel(index)} className={`${index===level?"active":""} ${completed.includes(index)?"complete":""}`}><span>{completed.includes(index)?<CheckCircle2/>:index+1}</span><small>{item.title}</small></button>)}</div>
    <main className="game-workbench"><section className="game-instructions"><div className="game-level-label">LEVEL {String(level+1).padStart(2,"0")}</div><h2>{current.title}</h2><p>{current.brief}</p><button className="game-hint-button" onClick={()=>setShowHint(!showHint)}><Lightbulb size={16}/>{showHint?current.hint:"Need a hint?"}</button><div className="game-target-label">Target layout</div><GameBoard level={current} style={current.solution}/></section>
      <section className="game-code-panel"><div className="code-toolbar"><span><Code2 size={15}/>CSS EDITOR</span><button onClick={()=>setCode(current.starter)}><RotateCcw size={14}/>Reset</button></div><div className="code-editor-wrap"><div className="code-lines">{code.split("\n").map((_,index)=><span key={index}>{index+1}</span>)}</div><textarea aria-label="CSS code editor" spellCheck={false} value={code} onChange={event=>{setCode(event.target.value);setWon(false)}}/></div><div className="game-actions"><span className={correct?"code-status ready":"code-status"}><i/>{correct?"Ready to submit":"Keep coding"}</span><button className="btn btn-primary" onClick={run}><Sparkles size={16}/>Check solution</button></div></section>
      <section className="game-preview"><div className="game-preview-head"><span>LIVE PREVIEW</span><span className="game-dots"><i/><i/><i/></span></div><div className="game-board-shell"><GameBoard level={current} style={liveStyle} itemStyle={parsed.item1GridColumn?{gridColumn:parsed.item1GridColumn}:undefined}/></div>{won&&<div className="game-win"><CheckCircle2/><div><strong>Perfect grid!</strong><span>You solved level {level+1}.</span></div>{level<levels.length-1&&<button onClick={()=>selectLevel(level+1)}>Next level<ArrowRight size={15}/></button>}</div>}</section>
    </main><div className="game-footer"><button disabled={level===0} onClick={()=>selectLevel(level-1)}><ArrowLeft/>Previous</button><span>Practice XP is saved on this device.</span><button disabled={level===levels.length-1} onClick={()=>selectLevel(level+1)}>Next<ArrowRight/></button></div>
  </div>;
}

function GameBoard({level,style,itemStyle}:{level:Level;style:React.CSSProperties|Record<string,string>;itemStyle?:React.CSSProperties}){const raw=style as Record<string,string>;const{item1GridColumn,...board}=raw;const resolved={display:"grid",...board} as React.CSSProperties;const firstStyle=itemStyle??(item1GridColumn?{gridColumn:item1GridColumn}:undefined);return <div className="grid-game-board" style={resolved}>{Array.from({length:level.items},(_,index)=><div className={`grid-game-item item-${index+1}`} style={index===0?firstStyle:undefined} key={index}><span>{level.labels[index]}</span></div>)}</div>}
