"use client";
import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Activity, ClipboardCheck, LayoutDashboard, ListPlus, LoaderCircle, LogOut, Plus, Send, Shield, Users } from "lucide-react";
import { toast } from "sonner";
import { createClient } from "@/lib/supabase/client";

type User = { id:string;fullName:string;username:string;email:string;level:number;xp:number;isAdmin:boolean;_count:{submissions:number} };
type Mission = { id:string;title:string;difficulty:string;xpReward:number;career:{name:string};_count:{submissions:number;assignments:number} };
type Submission = { id:string;status:string;score:number|null;githubUrl:string|null;liveUrl:string|null;explanation:string|null;updatedAt:string;user:{fullName:string;username:string};mission:{title:string} };
type Assignment = { id:string;note:string|null;dueAt:string|null;completed:boolean;user:{fullName:string;username:string};mission:{title:string} };
type Overview = {admin:{fullName:string};users:User[];missions:Mission[];submissions:Submission[];assignments:Assignment[]};

export default function AdminPage(){
 const router=useRouter(); const [data,setData]=useState<Overview|null>(null); const [token,setToken]=useState(""); const [tab,setTab]=useState("overview"); const [careers,setCareers]=useState<{id:string;name:string}[]>([]);
 const load=useCallback(async()=>{const {data:{session}}=await createClient().auth.getSession();if(!session){router.replace("/admin/login");return;}setToken(session.access_token);const headers={Authorization:`Bearer ${session.access_token}`};const [overview,meta]=await Promise.all([fetch("/api/admin/overview",{headers,cache:"no-store"}),fetch("/api/admin/missions",{headers})]);if(!overview.ok){router.replace("/admin/login");return;}setData(await overview.json());if(meta.ok)setCareers((await meta.json()).careers);},[router]);
 useEffect(()=>{queueMicrotask(()=>void load())},[load]);
 async function post(path:string,body:unknown){const response=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.message);await load();}
 async function createMission(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);try{await post("/api/admin/missions",{careerId:f.get("careerId"),title:f.get("title"),description:f.get("description"),scenario:f.get("scenario"),difficulty:f.get("difficulty"),xpReward:Number(f.get("xpReward")),estimatedMinutes:Number(f.get("estimatedMinutes"))});toast.success("Mission published.");event.currentTarget.reset();}catch(e){toast.error(e instanceof Error?e.message:"Could not create mission.")}}
 async function assign(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);try{await post("/api/admin/assignments",{userId:f.get("userId"),missionId:f.get("missionId"),note:f.get("note"),dueAt:f.get("dueAt")});toast.success("Task assigned.");}catch(e){toast.error(e instanceof Error?e.message:"Could not assign task.")}}
 async function review(id:string,status:"PASSED"|"NEEDS_REVISION"){const feedback=window.prompt(status==="PASSED"?"What did the learner do well?":"What should the learner improve?");if(!feedback)return;const score=Number(window.prompt("Score from 0 to 100",status==="PASSED"?"85":"60"));const response=await fetch(`/api/admin/submissions/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({status,score,feedback})});if(response.ok){toast.success("Review saved.");await load()}else toast.error((await response.json()).message)}
 async function logout(){await createClient().auth.signOut();router.replace("/admin/login")}
 if(!data)return <main className="admin-loading"><LoaderCircle className="animate-spin"/><h1 className="heading">Opening control room…</h1></main>;
 const tabs=[["overview",LayoutDashboard,"Overview"],["users",Users,"Users"],["missions",ListPlus,"Missions"],["projects",ClipboardCheck,"Projects"],["assign",Send,"Assign tasks"]] as const;
 return <main className="admin-shell"><aside className="admin-sidebar"><div className="admin-logo"><span><Shield/></span><div><strong className="heading">SkillVerse</strong><small>ADMIN CONSOLE</small></div></div><nav>{tabs.map(([id,Icon,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><Icon size={18}/>{label}</button>)}</nav><button className="admin-logout" onClick={logout}><LogOut size={17}/>Sign out</button></aside><section className="admin-main"><header><div><div className="eyebrow">Operations center</div><h1 className="heading">{tabs.find(item=>item[0]===tab)?.[2]}</h1></div><div className="admin-identity"><span>{data.admin.fullName.slice(0,1)}</span><div><strong>{data.admin.fullName}</strong><small>Administrator</small></div></div></header>
 {tab==="overview"&&<><div className="admin-stats"><article className="card"><Users/><span>Members</span><strong className="heading">{data.users.length}</strong></article><article className="card"><ListPlus/><span>Missions</span><strong className="heading">{data.missions.length}</strong></article><article className="card"><ClipboardCheck/><span>Projects</span><strong className="heading">{data.submissions.length}</strong></article><article className="card"><Activity/><span>Active tasks</span><strong className="heading">{data.assignments.filter(item=>!item.completed).length}</strong></article></div><section className="card admin-section"><div className="admin-section-title"><div><div className="eyebrow">Latest activity</div><h2>Recent project submissions</h2></div></div><ProjectTable submissions={data.submissions.slice(0,6)} review={review}/></section></>}
 {tab==="users"&&<section className="card admin-section"><div className="admin-section-title"><h2>All members</h2><span className="badge">{data.users.length} accounts</span></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Member</th><th>Level</th><th>XP</th><th>Projects</th><th>Role</th></tr></thead><tbody>{data.users.map(u=><tr key={u.id}><td><strong>{u.fullName}</strong><small>@{u.username} · {u.email}</small></td><td>{u.level}</td><td>{u.xp}</td><td>{u._count.submissions}</td><td><span className="badge">{u.isAdmin?"Admin":"Member"}</span></td></tr>)}</tbody></table></div></section>}
 {tab==="missions"&&<div className="admin-split"><form className="card admin-form" onSubmit={createMission}><div className="admin-section-title"><h2>Create mission</h2><Plus/></div><label>Career<select className="field" name="careerId" required>{careers.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Mission title<input className="field" name="title" required/></label><label>Description<textarea className="field" name="description" rows={3} required/></label><label>Client scenario<textarea className="field" name="scenario" rows={3} required/></label><div className="auth-row"><label>Difficulty<select className="field" name="difficulty"><option>BEGINNER</option><option>INTERMEDIATE</option><option>ADVANCED</option><option>BOSS</option></select></label><label>XP reward<input className="field" name="xpReward" type="number" defaultValue="250"/></label></div><label>Estimated minutes<input className="field" name="estimatedMinutes" type="number" defaultValue="180"/></label><button className="btn btn-primary">Publish mission</button></form><section className="card admin-section"><h2>Mission library</h2><div className="admin-list">{data.missions.map(m=><article key={m.id}><div><strong>{m.title}</strong><small>{m.career.name} · {m.difficulty}</small></div><span>{m.xpReward} XP</span></article>)}</div></section></div>}
 {tab==="projects"&&<section className="card admin-section"><div className="admin-section-title"><h2>Project review queue</h2><span className="badge">{data.submissions.length} submissions</span></div><ProjectTable submissions={data.submissions} review={review}/></section>}
 {tab==="assign"&&<div className="admin-split"><form className="card admin-form" onSubmit={assign}><div className="admin-section-title"><h2>Give a new task</h2><Send/></div><label>Member<select className="field" name="userId">{data.users.filter(u=>!u.isAdmin).map(u=><option value={u.id} key={u.id}>{u.fullName} (@{u.username})</option>)}</select></label><label>Mission<select className="field" name="missionId">{data.missions.map(m=><option value={m.id} key={m.id}>{m.title}</option>)}</select></label><label>Admin note<textarea className="field" name="note" rows={4} placeholder="Focus areas, expectations, or helpful context"/></label><label>Due date<input className="field" name="dueAt" type="date"/></label><button className="btn btn-primary">Assign mission</button></form><section className="card admin-section"><h2>Assigned work</h2><div className="admin-list">{data.assignments.map(a=><article key={a.id}><div><strong>{a.mission.title}</strong><small>{a.user.fullName} · {a.dueAt?new Date(a.dueAt).toLocaleDateString():"No due date"}</small></div><span className="badge">{a.completed?"Done":"Active"}</span></article>)}</div></section></div>}
 </section></main>;
}

function ProjectTable({submissions,review}:{submissions:Submission[];review:(id:string,status:"PASSED"|"NEEDS_REVISION")=>void}){return <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Learner</th><th>Project</th><th>Status</th><th>Links</th><th>Review</th></tr></thead><tbody>{submissions.map(s=><tr key={s.id}><td><strong>{s.user.fullName}</strong><small>@{s.user.username}</small></td><td><strong>{s.mission.title}</strong><small>{new Date(s.updatedAt).toLocaleDateString()}</small></td><td><span className="badge">{s.status.replace("_"," ")}</span></td><td>{s.githubUrl&&<a href={s.githubUrl} target="_blank" rel="noreferrer">GitHub</a>} {s.liveUrl&&<a href={s.liveUrl} target="_blank" rel="noreferrer">Live</a>}</td><td><div className="admin-review"><button onClick={()=>review(s.id,"PASSED")}>Approve</button><button onClick={()=>review(s.id,"NEEDS_REVISION")}>Revise</button></div></td></tr>)}</tbody></table>{!submissions.length&&<div className="admin-empty">No submitted projects yet.</div>}</div>}
