"use client";

import { BriefcaseBusiness, ExternalLink, Github, LoaderCircle, MapPin, Plus, Save, ShieldCheck, Sparkles, UserRound, X } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { createClient } from "@/lib/supabase/client";
import { useRouter } from "next/navigation";

type Profile = { fullName:string; username:string; email:string; bio:string; headline:string; phone:string; gender:string; location:string; skills:string[]; githubUrl:string; linkedinUrl:string; isPublic:boolean; soundEnabled:boolean; terminalTheme:string; career:string };
const empty:Profile = {fullName:"",username:"",email:"",bio:"",headline:"",phone:"",gender:"",location:"",skills:[],githubUrl:"",linkedinUrl:"",isPublic:true,soundEnabled:true,terminalTheme:"aurora",career:"No career selected"};

export default function Page() {
  const router=useRouter(); const[profile,setProfile]=useState<Profile>(empty); const[skill,setSkill]=useState(""); const[loading,setLoading]=useState(true); const[saving,setSaving]=useState(false);
  useEffect(()=>{void(async()=>{try{const{data:{session}}=await createClient().auth.getSession();if(!session)throw new Error("Please log in to manage your profile.");const response=await fetch("/api/profile",{cache:"no-store",headers:{Authorization:`Bearer ${session.access_token}`}});const data=await response.json();if(!response.ok)throw new Error(data.message);if(!data.profile){router.replace("/onboarding");return}const item=data.profile;setProfile({fullName:item.fullName||data.auth.fullName||"",username:item.username||data.auth.username||"",email:item.email||data.auth.email||"",bio:item.bio||"",headline:item.headline||"",phone:item.phone||"",gender:item.gender||"",location:item.location||"",skills:item.skills||[],githubUrl:item.githubUrl||"",linkedinUrl:item.linkedinUrl||"",isPublic:item.isPublic??true,soundEnabled:item.soundEnabled??true,terminalTheme:item.terminalTheme||"aurora",career:item.careers?.[0]?.career?.name||"No career selected"})}catch(error){toast.error(error instanceof Error?error.message:"Could not load your profile.")}finally{setLoading(false)}})()},[router]);
  function addSkill(){const value=skill.trim();if(!value)return;if(profile.skills.some(item=>item.toLowerCase()===value.toLowerCase())){toast.error("That skill is already listed.");return}if(profile.skills.length>=20){toast.error("You can add up to 20 skills.");return}setProfile({...profile,skills:[...profile.skills,value]});setSkill("")}
  async function save(event:React.FormEvent){event.preventDefault();setSaving(true);try{const{data:{session}}=await createClient().auth.getSession();if(!session)throw new Error("Please log in again.");const response=await fetch("/api/profile",{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify(profile)});const data=await response.json();if(!response.ok)throw new Error(data.message);toast.success("Your profile has been updated.")}catch(error){toast.error(error instanceof Error?error.message:"Could not save your profile.")}finally{setSaving(false)}}
  if(loading)return <><div className="eyebrow">Account configuration</div><h1 className="heading" style={{fontSize:42}}>Settings</h1><div className="card dashboard-state" style={{marginTop:28}}><LoaderCircle className="animate-spin"/></div></>;
  return <><div className="eyebrow">Account configuration</div><h1 className="heading" style={{fontSize:42,marginBottom:8}}>Build your profile</h1><p className="muted">Tell people who you are, what you do, and which skills you bring.</p><form onSubmit={save} className="settings-layout">
    <div className="settings-profile-stack">
      <section className="card settings-profile-card"><div className="settings-title"><span><UserRound size={20}/></span><div><h2>Personal details</h2><p>Your identity and contact information.</p></div></div><div className="grid-2"><label>Full name<input className="field" value={profile.fullName} onChange={e=>setProfile({...profile,fullName:e.target.value})}/></label><label>Username<input className="field mono" value={profile.username} onChange={e=>setProfile({...profile,username:e.target.value})}/></label></div><label>Email address<input className="field" value={profile.email} disabled/><small className="muted">Managed securely by Supabase Authentication.</small></label><div className="grid-2"><label>Contact number<input className="field" type="tel" autoComplete="tel" placeholder="+92 300 1234567" value={profile.phone} onChange={e=>setProfile({...profile,phone:e.target.value})}/></label><label>Location<input className="field" autoComplete="address-level2" placeholder="Karachi, Pakistan" value={profile.location} onChange={e=>setProfile({...profile,location:e.target.value})}/></label></div><label>Gender<select className="field styled-select" value={profile.gender} onChange={e=>setProfile({...profile,gender:e.target.value})}><option value="">Select gender</option><option value="female">Female</option><option value="male">Male</option><option value="non-binary">Non-binary</option><option value="prefer-not-to-say">Prefer not to say</option></select></label></section>
      <section className="card settings-profile-card"><div className="settings-title"><span><BriefcaseBusiness size={20}/></span><div><h2>Professional profile</h2><p>A concise introduction for recruiters and collaborators.</p></div></div><label>Professional headline<input className="field" maxLength={100} placeholder="Full-stack developer building reliable web products" value={profile.headline} onChange={e=>setProfile({...profile,headline:e.target.value})}/><small className="muted">{profile.headline.length}/100 characters</small></label><label>About you<textarea className="field" rows={6} maxLength={300} placeholder="Share your experience, interests, working style, and what you want to build next." value={profile.bio} onChange={e=>setProfile({...profile,bio:e.target.value})}/><small className="muted">{profile.bio.length}/300 characters</small></label><div className="grid-2"><label>GitHub URL<input className="field" type="url" placeholder="https://github.com/username" value={profile.githubUrl} onChange={e=>setProfile({...profile,githubUrl:e.target.value})}/></label><label>LinkedIn URL<input className="field" type="url" placeholder="https://linkedin.com/in/username" value={profile.linkedinUrl} onChange={e=>setProfile({...profile,linkedinUrl:e.target.value})}/></label></div></section>
      <section className="card settings-profile-card"><div className="settings-title"><span><Sparkles size={20}/></span><div><h2>Skills</h2><p>Add technologies, tools, and professional capabilities.</p></div></div><div className="skill-entry"><input className="field" value={skill} maxLength={40} placeholder="e.g. React, Figma, Node.js" onChange={e=>setSkill(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();addSkill()}}}/><button className="btn btn-ghost" type="button" onClick={addSkill}><Plus size={17}/>Add skill</button></div><div className="editable-skill-cloud">{profile.skills.map(item=><span key={item}>{item}<button type="button" aria-label={`Remove ${item}`} onClick={()=>setProfile({...profile,skills:profile.skills.filter(value=>value!==item)})}><X size={13}/></button></span>)}{!profile.skills.length&&<p className="muted">No skills added yet. Add your strongest capabilities first.</p>}</div></section>
      <button disabled={saving} className="btn btn-primary settings-save">{saving?<LoaderCircle className="animate-spin" size={17}/>:<Save size={17}/>} {saving?"Saving changes…":"Save all profile details"}</button>
    </div>
    <aside className="settings-side"><section className="card"><div className="settings-title compact"><span><ShieldCheck size={19}/></span><div><h2>Preferences</h2><p>{profile.career}</p></div></div><label className="toggle-row"><span><strong>Public profile</strong><small>Allow recruiters to view your work.</small></span><input type="checkbox" checked={profile.isPublic} onChange={e=>setProfile({...profile,isPublic:e.target.checked})}/></label><label className="toggle-row"><span><strong>Sound effects</strong><small>Play subtle achievement sounds.</small></span><input type="checkbox" checked={profile.soundEnabled} onChange={e=>setProfile({...profile,soundEnabled:e.target.checked})}/></label><label>Terminal theme<select className="field styled-select" value={profile.terminalTheme} onChange={e=>setProfile({...profile,terminalTheme:e.target.value})}><option value="aurora">Aurora Dark</option><option value="midnight">Midnight</option><option value="monochrome">Monochrome</option></select></label></section>{profile.username&&<Link href={`/u/${profile.username}`} className="card profile-preview-link"><Github size={20}/><div><strong>View public profile</strong><p>Preview your recruiter-facing page.</p></div><ExternalLink size={16}/></Link>}<section className="card settings-tip"><MapPin/><div><strong>Profile quality tip</strong><p>A headline, location, and 5–10 focused skills make your profile easier to understand.</p></div></section></aside>
  </form></>;
}
