"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowRight, CalendarDays, CheckCircle2, ClipboardList, Clock3, LoaderCircle, ShieldCheck, Sparkles, Star } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Task = { id:string;note:string|null;dueAt:string|null;completed:boolean;createdAt:string;mission:{slug:string;title:string;description:string;scenario:string;difficulty:string;xpReward:number;estimatedMinutes:number;career:{name:string}};assignedBy:{fullName:string} };
export default function TasksPage(){
 const [tasks,setTasks]=useState<Task[]|null>(null);const [error,setError]=useState("");const [filter,setFilter]=useState<"all"|"active"|"completed">("all");
 useEffect(()=>{void createClient().auth.getSession().then(async({data:{session}})=>{if(!session)throw new Error("Please sign in to view your tasks.");const response=await fetch("/api/tasks",{cache:"no-store",headers:{Authorization:`Bearer ${session.access_token}`}});const result=await response.json();if(!response.ok)throw new Error(result.message);setTasks(result.tasks)}).catch(caught=>setError(caught instanceof Error?caught.message:"Could not load assigned tasks."))},[]);
 const shown=useMemo(()=>tasks?.filter(task=>filter==="all"||(filter==="completed"?task.completed:!task.completed))??[],[tasks,filter]);
 if(error)return <div className="card dashboard-state"><ClipboardList/><h1 className="heading">Tasks unavailable</h1><p>{error}</p></div>;
 if(!tasks)return <div className="card dashboard-state"><LoaderCircle className="animate-spin"/><h2 className="heading">Loading assigned tasks…</h2><p>Checking your latest work from the admin team.</p></div>;
 const active=tasks.filter(task=>!task.completed).length;
 return <><div className="task-page-heading"><div><div className="eyebrow">Direct assignments · {active} active</div><h1 className="heading">Your assigned tasks.</h1><p>Focused missions selected for you by the SkillVerse admin team.</p></div><div className="task-summary"><ClipboardList/><span><strong>{tasks.length}</strong><small>Total assigned</small></span></div></div><div className="mission-filters task-filters">{(["all","active","completed"] as const).map(item=><button key={item} onClick={()=>setFilter(item)} className={filter===item?"active":""}>{item[0].toUpperCase()+item.slice(1)}</button>)}</div>
 <div className="task-grid">{shown.map(task=><article className={`card assigned-task ${task.completed?"completed":""}`} key={task.id}><div className="assigned-task-top"><span className="badge">{task.mission.difficulty}</span><span className={`mission-status ${task.completed?"done":"ready"}`}>{task.completed?<><CheckCircle2 size={14}/>Completed</>:<><Sparkles size={14}/>Assigned</>}</span></div><div><div className="eyebrow">{task.mission.career.name}</div><h2 className="heading">{task.mission.title}</h2><p>{task.mission.description}</p></div>{task.note&&<blockquote><ShieldCheck size={17}/><div><strong>Note from {task.assignedBy.fullName}</strong><p>{task.note}</p></div></blockquote>}<div className="assigned-task-meta"><span><Star size={14}/>{task.mission.xpReward} XP</span><span><Clock3 size={14}/>{Math.round(task.mission.estimatedMinutes/60)}h estimate</span><span className={task.dueAt&&new Date(task.dueAt)<new Date()&&!task.completed?"overdue":""}><CalendarDays size={14}/>{task.dueAt?`Due ${new Date(task.dueAt).toLocaleDateString()}`:"No deadline"}</span></div>{!task.completed&&<Link href={`/dashboard/missions/${task.mission.slug}`} className="btn btn-primary">Open mission<ArrowRight size={17}/></Link>}</article>)}</div>
 {!shown.length&&<div className="card task-empty"><CheckCircle2/><h2 className="heading">{filter==="active"?"You’re all caught up.":"No tasks here yet."}</h2><p>{filter==="active"?"Your admin has not assigned any unfinished work.":"New assignments will appear here automatically."}</p></div>}</>;
}
